apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: estanr2j1-nodejs-gitops
  description: This is GitOps manifest for estanr2j1-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=estanr2j1-nodejs
    backstage.io/kubernetes-id: estanr2j1-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: estanr2j1-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:estanr2j1-nodejs
