apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: estanr2j1-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-253bd3e2f0.hdtj.p3.openshiftapps.com/rhtap/rhtap-qe:046b2b60d835d44c33f327da7240254dea01a731@sha256:09bb275b646449ed4841763d3e2abe4fbacccc882432c54cba9d78c86f47b18f
          name: container-image
